upadte pipeline

diff --git a/.github/workflows/db_mgration.yml b/.github/workflows/db_mgration.yml
--- a/.github/workflows/db_mgration.yml
+++ b/.github/workflows/db_mgration.yml
@@ -1,3 +1,4 @@
+<<<<<<< HEAD:.github/workflows/db_mgration.yml
 name: Intializing Database
 
 on:
@@ -64,4 +65,72 @@ jobs:
             echo "::error::Database Creation Failed $FAILED instance(s)!" && \
             exit 1
 
+=======
+name: Intializing Database
+
+on:
+  workflow_dispatch:
+
+permissions:
+  id-token: write
+  contents: read
+
+jobs:
+  init-db:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: vishwajeet937/Banking
+          ref: main
+
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::812616070174:role/github-action-deploy-role
+          aws-region: us-east-1
+
+      - name: Upload file on S3
+        run: |
+          aws s3 mb s3://812616070174-devops-scripts --region us-east-1 2>/dev/null || true
+          aws s3 cp init.sql s3://812616070174-devops-scripts/init.sql --region us-east-1
+          aws s3 cp init.py s3://812616070174-devops-scripts/init.py --region us-east-1
+          echo "✅ Files Uploaded to bucket.."
+
+      - name: Initializing Database on RDS using Ec2
+        id: init
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://812616070174-devops-scripts/init.py /tmp/init.py",
+              "python3 /tmp/init.py || exit 1",
+              "rm /tmp/init.py"
+            ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1)
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+          [ "$FAILED" -gt 0 ] && \
+            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
+            exit 1
+
+>>>>>>> 9533ddf (upadte pipeline):.github/workflows/db_migration.yml
           echo "✅ Database Created Successfully"
diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -1,3 +1,4 @@
+<<<<<<< HEAD
 name: Test Fleet health and Env Variables
 
 on:
@@ -67,3 +68,65 @@ jobs:
           fi
 
           echo "✅ All Instances Healthy"
+=======
+name: Test Fleet health and Env Variables
+
+on:
+  workflow_dispatch:
+
+
+permissions:
+  id-token: write
+  contents: read
+
+jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::812616070174:role/github-action-deploy-role
+          aws-region: us-east-1
+
+      - name: Fleet Health Checks
+        id: health
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "hostname -I",
+              "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
+              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1 | grep -E Name"
+              ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1
+            )
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+      
+      
+      - name: Show Results
+        run: |  
+          sleep 20
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text 
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1
+            )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
+          exit 1
+
+          echo "ALL Instances Healthy ✅"
+>>>>>>> 9533ddf (upadte pipeline)
