update pipeline

diff --git a/.github/workflows/db_mgration.yml b/.github/workflows/db_mgration.yml
--- a/.github/workflows/db_mgration.yml
+++ b/.github/workflows/db_mgration.yml
@@ -1,7 +1,7 @@
 name: Intializing Database
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
 
 permissions:
   id-token: write
@@ -24,6 +24,44 @@ jobs:
       - name: Upload file on S3
         run: |
           aws s3 mb s3://812616070174-devops-scripts --region us-east-1 2>/dev/null || true
-          aws s3 cp init.sql s3://812616070174-devops-scripts/init.sql 
-          aws s3 cp init.py s3://812616070174-devops-scripts/init.py 
+          aws s3 cp init.sql s3://812616070174-devops-scripts/init.sql --region us-east-1
+          aws s3 cp init.py s3://812616070174-devops-scripts/init.py --region us-east-1
           echo "✅ Files Uploaded to bucket.."
+
+      - name: Initializing Database on RDS using Ec2
+        id: init
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://812616070174-devops-scripts/init.py /tmp/init.py",
+              "python3 /tmp/init.py || exit 1",
+              "rm /tmp/init.py"
+            ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1)
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+          [ "$FAILED" -gt 0 ] && \
+            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
+            exit 1
+
+          echo "✅ Database Created Successfully"
