update pipeline

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -39,25 +39,31 @@ jobs:
       
       - name: Show Results
         run: |
-         sleep 20
+          sleep 20
 
-         aws ssm list-command-invocations \
-           --command-id "${{ steps.health.outputs.cmd_id }}" \
-           --details \
-           --region us-east-1 \
-           --output text
+          INSTANCE_ID=$(aws ec2 describe-instances \
+            --filters "Name=tag:App,Values=flask" \
+            --query "Reservations[0].Instances[0].InstanceId" \
+            --output text \
+            --region us-east-1)
 
-         STATUS=$(aws ssm list-command-invocations \
-           --command-id "${{ steps.health.outputs.cmd_id }}" \
-           --query "CommandInvocations[0].Status" \
-           --output text \
-           --region us-east-1)
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --instance-id "$INSTANCE_ID" \
+            --query "Status" \
+            --output text \
+            --region us-east-1)
 
-         echo "Command Status: $STATUS"
+          echo "Command Status: $STATUS"
 
-         if [ "$STATUS" != "Success" ]; then
-         echo "::error::Health Check Failed. Status: $STATUS"
-         exit 1
-         fi
+          aws ssm get-command-invocation \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --instance-id "$INSTANCE_ID" \
+            --region us-east-1
 
-         echo "✅ All Instances Healthy"
+          if [ "$STATUS" != "Success" ]; then
+          echo "::error::Health Check Failed. Status: $STATUS"
+          exit 1
+          fi
+
+          echo "✅ All Instances Healthy"
